Require --template-id for check command

diff --git a/commands/migration/externalids-check b/commands/migration/externalids-check
--- a/commands/migration/externalids-check
+++ b/commands/migration/externalids-check
@@ -90,7 +90,14 @@ while [ $# -gt 0 ]; do
     esac
     shift
 done
+
 set -- "${POSITIONAL_ARGS[@]}"
+
+# Check if ID template is provided
+if [ -z "$ID_TEMPLATE" ]; then
+    error "The --id-template argument is required." "See 'c8y dtm migration externalids-create --help' for details."
+    exit 1
+fi
 
 # List of allowed global/inherited flags for c8y identity list (short and long forms)
 export ALLOWED_FLAGS=(
